#!/bin/sh

scrot '%Y-%m-%d_%H%M%S_$wx$h.png' -e 'mv $f ~/Pictures && convert -thumbnail x128 ~/Pictures/$f /tmp/$f && readlink -f ~/Pictures/$f | xargs -I "{}" notify-send -u low "Screen saved as {}" -i /tmp/$f'
